### ISSUE TITLE
install.sh errors for Service Dialogs and Buttons.

### ISSUE THREAD

**Issue by jeffmcutter** [rhtconsulting/miq-BASE#2]
ServiceDialogs and Buttons directories do not exist, but install.sh tries to install them, generating errors.

[root@cfme07 miq-BASE-master]# sh install.sh
Importing miq-Marketplace from /tmp/miq-BASE-master/Automate/miq-Marketplace
Importing Service Dialogs
rake aborted!
Errno::ENOENT: No such file or directory - /tmp/miq-BASE-master/ServiceDialogs
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:17:in `open'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:17:in`foreach'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:17:in `block in import'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/transactions.rb:208:in `transaction'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:16:in`import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:125:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:dialogs:import
(See full trace by running task with --trace)
Importing Buttons
rake aborted!
Errno::ENOENT: No such file or directory - /tmp/miq-BASE-master/Buttons/buttons.yml
/opt/rh/ruby200/root/usr/share/gems/gems/psych-2.0.13/lib/psych.rb:464:in`initialize'
/opt/rh/ruby200/root/usr/share/gems/gems/psych-2.0.13/lib/psych.rb:464:in `open'
/opt/rh/ruby200/root/usr/share/gems/gems/psych-2.0.13/lib/psych.rb:464:in`load_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:5:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:231:in`block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:buttons:import
(See full trace by running task with --trace)
[root@cfme07 miq-BASE-master]#

**Comment by jsimonelli** [comment]
FIxed.  This was from a previous version where ServiceDialogs and Buttons still were here before being moved to the corresponding project it was extracted to.

Commented out those commands to skip importing those as they no longer exist with commit https://github.com/rhtconsulting/miq-BASE/commit/06ec1eef841f5024efc709e4a34109cb28e4130f#diff-3fbb47e318cd8802bd325e7da9aaabe8
